<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CampSite;

class CampSiteSeeder extends Seeder
{
    public function run(): void
    {
        $camps = [
            [
                'name' => 'Sungai Lepoh Eco Camp',
                'description' => 'Tempat camping tepi sungai dengan air yang jernih dan suasana hutan.',
                'state' => 'Selangor',
                'address' => 'Hulu Langat, Selangor',
                'latitude' => 3.1683,
                'longitude' => 101.8165,
                'image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => true,
                'has_electricity' => false,
                'has_bbq' => true,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'Hammocks by the River',
                'description' => 'Camp santai tepi sungai dengan hammock dan BBQ pit tersedia.',
                'state' => 'Pahang',
                'address' => 'Bentong, Pahang',
                'latitude' => 3.4602,
                'longitude' => 101.7989,
                'image' => 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => true,
                'has_electricity' => true,
                'has_bbq' => true,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'Tiarasa Escapes Glamping Resort',
                'description' => 'Glamping mewah di Janda Baik dengan khemah eksklusif dan sungai kecil.',
                'state' => 'Pahang',
                'address' => 'Janda Baik, Bentong',
                'latitude' => 3.3331,
                'longitude' => 101.8279,
                'image' => 'https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => true,
                'has_electricity' => true,
                'has_bbq' => false,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'Sungai Congkak Eco Resort',
                'description' => 'Tapak camping luas berhampiran sungai Congkak, sesuai untuk keluarga.',
                'state' => 'Selangor',
                'address' => 'Hulu Langat, Selangor',
                'latitude' => 3.1700,
                'longitude' => 101.8344,
                'image' => 'https://images.unsplash.com/photo-1523413363574-c30aa1c2a516?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => true,
                'has_electricity' => true,
                'has_bbq' => true,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'Endau-Rompin National Park Camp',
                'description' => 'Pengalaman camping sebenar di hutan hujan tropika Johor.',
                'state' => 'Johor',
                'address' => 'Kahang, Johor',
                'latitude' => 2.4896,
                'longitude' => 103.3069,
                'image' => 'https://images.unsplash.com/photo-1502920917128-1aa500764b43?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => false,
                'has_river' => true,
                'has_electricity' => false,
                'has_bbq' => false,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'Camp Out Port Dickson',
                'description' => 'Tapak khemah tepi pantai dengan pemandangan matahari terbenam.',
                'state' => 'Negeri Sembilan',
                'address' => 'Teluk Kemang, Port Dickson',
                'latitude' => 2.4839,
                'longitude' => 101.8447,
                'image' => 'https://images.unsplash.com/photo-1534081333815-ae5019106622?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => false,
                'has_electricity' => true,
                'has_bbq' => true,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'Eco Rimba Ulu Kedongdong',
                'description' => 'Air terjun dan hutan tropika yang menenangkan.',
                'state' => 'Selangor',
                'address' => 'Batang Kali, Selangor',
                'latitude' => 3.4060,
                'longitude' => 101.7403,
                'image' => 'https://images.unsplash.com/photo-1499696010181-8ab5076e67ab?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => true,
                'has_electricity' => false,
                'has_bbq' => false,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'The Hooton Retreat',
                'description' => 'Tempat glamping moden dengan pemandangan hijau di Jelebu.',
                'state' => 'Negeri Sembilan',
                'address' => 'Jelebu, Negeri Sembilan',
                'latitude' => 2.9417,
                'longitude' => 102.0364,
                'image' => 'https://images.unsplash.com/photo-1529692236671-f1dc28a3aa0e?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => false,
                'has_electricity' => true,
                'has_bbq' => true,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'Tandop Hills Camp',
                'description' => 'Tapak camping berbukit dengan udara segar di Kedah.',
                'state' => 'Kedah',
                'address' => 'Alor Setar, Kedah',
                'latitude' => 6.1284,
                'longitude' => 100.3679,
                'image' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => false,
                'has_electricity' => true,
                'has_bbq' => false,
                'is_approved' => true,
                'user_id' => 1,
            ],
            [
                'name' => 'Penang Hill Eco Camp',
                'description' => 'Camping dengan pemandangan indah Pulau Pinang dari atas bukit.',
                'state' => 'Pulau Pinang',
                'address' => 'Bukit Bendera, Penang',
                'latitude' => 5.4141,
                'longitude' => 100.2760,
                'image' => 'https://images.unsplash.com/photo-1528892952291-009c663ce843?auto=format&fit=crop&w=800&q=80',
                'has_toilet' => true,
                'has_river' => false,
                'has_electricity' => true,
                'has_bbq' => true,
                'is_approved' => true,
                'user_id' => 1,
            ],
        ];

        foreach ($camps as $camp) {
            CampSite::create($camp);
        }
    }
}
